name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Please provide a detailed description of the feature.
      placeholder: Describe the feature you are requesting.
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: What is the main purpose of this feature? Why is it needed?
      placeholder: Explain the purpose of the feature.
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Provide any relevant context or background information for this feature.
      placeholder: Provide background information.
    validations:
      required: false

  - type: textarea
    id: expected_outcome
    attributes:
      label: Expected Outcome
      description: What are the expected results of implementing this feature?
      placeholder: Explain the expected results or impact.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true